### ISSUE TITLE
Cutover checklist

### ISSUE THREAD

**Issue by jessicaschilling** [ipfs/ipfs-website#16]
Holding pen for items that need to be confirmed/changed just prior to or at time of launch. Please add any new items directly to this comment rather than in subsequent comments. We can break these out into separate issues as needed.

- [x] Approval for visual continuity (will defer to @atopal as to high up the executive chain this needs to go), plus addition of NFT text in "here and now" section
- [x] DNS cutover, including any considerations for general ipfs.io gateway behavior (@andyschwab is managing)
- [x] Check all page URLs display correctly, plus 404
- [x] Migrate any issues still in https://github.com/ipfs/website/ repo to this repo
- [x] Make sure this repo's readme is correct and useful
- [x] Close any stray dependabot issues/PRs
- [x] Add standard issue templates
- [x] Protect any branches that need to be protected
- [x] Remove any permissions not necessary after making repo public
- [x] Confirm Countly is using correct data and dashboard is working; switch on email reports
- [x] Make sure Dinesh knows metrics are now coming from Countly
- [x] Confirm Speedcurve is using correct data
- [x] Confirm social cards display correctly, particularly image as that's an absolute path and can't be tested in advance
- [x] Send internal email and create meeting slide
- [ ]  _(scheduled for 1 July for safety net)_ Move repo to `ipfs-inactive` org; confirm that https://github.com/ipfs/website/tree/master/static/docs and items within redirect correctly into the archived repo

**Comment by jessicaschilling** [comment]
I've got a calendar reminder in to move the old repo into `ipfs-inactive`; we're good to close this one.
