### ISSUE TITLE
setup application base

### ISSUE THREAD

**Issue by cwaring** [ipfs/ipfs-website#180]
```[tasklist]
### Tasks
- [x] setup pnpm and new package.json
- [x] setup Nuxt 3 and main routes
- [x] add base modules (exp via layer)
- [x] add unocss config
- [x] add eslint config
- [x] add tsconfig
- [x] fix existing routes
```
